### PR TITLE
Bioinfo related bed files

### PR DESCRIPTION
**Pull request by hassanfa**
@henrikstranneheim 

Started creating placeholders. Feel free to add/change/remove.

### CODE REVIEW

**Comment by annaengstrom** [comment]
Is MIP and Balsamic kept separate as different sections because some bed files might be different?

**Comment by hassanfa** [comment]
The source will be the same (the ones we keep adding), but the actual bed file used in the analysis could be different (having chr or not, split per chromosome, add custom annotation, etc)

**Comment by annaengstrom** [comment]
Ok, looks good! Happy merging!

**Comment by hassanfa** [comment]
I'm merging this into master feel free to make a PR or add changes for mip's bedfiles whenever you have time.

**Pull request merged**
