### PR TITLE
Extract regions from panels

### PR DESCRIPTION
**Pull request by keyvanelhami**
Below script is used to get information regarding which regions in a gene that are included in a specific panel. The output should be a text file where the regions with coverage >50X (coverage values taken from Sambamba) are extracted with the exact chromosome position and the rs-id (RefSNPs-id).

Follow below instruction to test the new script locally on your computer.

Download Miniconda and set-up conda environment

- [x] Download Miniconda from following site: https://docs.conda.io/en/latest/miniconda.html
- [x] Run: `bash Miniconda3-latest-MacOSX-x86_64.sh` to install Miniconda
- [x] Check if conda is installed correctley by writing `conda list`
- [x] Create a conda environment: `conda create --name balsamic_tools`
- [x] Activate your conda environment: `source activate balsamic_tools`

Install softwares to your conda environment in your locally computer

- [x] bcftools v1.9: `conda install -c bioconda bcftools`
- [x] bedops v2.4.35 `conda install -c bioconda bedops`
- [x] tabix v0.2.6 `conda install -c bioconda tabix`
- [x] samtools v1.9 `conda install -c bioconda samtools`
- [x] sambamba v0.6.6 `conda install -c bioconda sambamba`
- [x] snakemake v5.9.1 `conda install -c bioconda snakemake`

Download following files from hasta to an optional directory on your local computer:

- [x] `/home/proj/production/cancer/cases/mintpossum_20M/analysis/bam/concatenated_ACC5812A1_XXXXXX_R.sorted.bam`
- [x] `/home/proj/production/cancer/cases/mintpossum_20M/analysis/bam/concatenated_ACC5812A1_XXXXXX_R.sorted.bam.bai` 
- [x] `/home/proj/production/cancer/reference/GRCh37/variants/dbsnp_grch37_b138.vcf.gz`

Download the files from Github:

- [x] In github, Clone by clicking on "Clone or Download" and then `git clone <TheCopiedPath>`
- [x] Update the branch `git pull`
- [x] Change branch: `git checkout Extract_regions_from_panels`
- [x] Check that you are on the correct branch `git branch`

Run the snakemake file:

- [x] Change the config.json to "ACC5812A1" instead of "LimsID"
- [x] Change the config.json to "mintpossum" instead of "CaseID" 
- [x] Change the path in config.json in "dbsnp_vcf" to the path where the dnsnp.vcf is saved
- [x] Change the path in config.json in "path_to_case" to the path where the case directory is created
- [x] Run snakemake as dry-run: `snakemake -s -n Extract_regions_from_panel-design`
- [x] If now errors occur, run snakemake: `snakemake -s Extract_regions_from_panel-design`

Check the output file:
- [x] The output file should look like this: [ACC5812A1_1_97543299_98386605_Sambamba_cov_Above50.txt](https://github.com/Clinical-Genomics/target_capture_bed/files/4071490/ACC5812A1_1_97543299_98386605_Sambamba_cov_Above50.txt)

### CODE REVIEW

**Comment by keyvanelhami** [comment]
@hassanfa Please read through the instructions and come back to me if something is missing. When the instructions are ready, I will let @annaengstrom test the code

**Comment by annaengstrom** [comment]
I had Miniconda3 installed already so I updated with:

conda update conda

to version 4.8.1

**Comment by annaengstrom** [comment]
I have done the installations however some version differ from the ones in the list above. For the following tools I have these versions.

bedops v2.4.37
tabix v0.2.5 
snakemake v3.13.3

Should I fix it to the ones above or go ahead anyway? @keyvanelhami

**Comment by hassanfa** [comment]
bedops and tabix are fine. Snakemake is going to be an issue. Try activating your conda environment, `conda install pip`, and then `pip install snakemake==5.9.1`

**Comment by hassanfa** [comment]
Or you could also try `conda install -c conda-forge -c bioconda snakemake=5.8.1`

**Comment by annaengstrom** [comment]
Thanks! Done, I have snakemake 5.9.1 now.

I have access to hasta but I not used it, a short demo could probably be useful. @keyvanelhami?

**Comment by keyvanelhami** [comment]
> Thanks! Done, I have snakemake 5.9.1 now.
> 
> I have access to hasta but I have not used it, a short demo could probably be useful. @keyvanelhami?

Sure, come to my desk when you have time and we can go through Hasta

**Comment by keyvanelhami** [comment]
@annaengstrom How is the process going? Do you have any idea when you will have time to test this? We are in the next phase and would like to test that script too

**Comment by annaengstrom** [comment]
Done, this is my output file
[ACC5812A1_1_97543299_98386605_Sambamba_cov_Above50.txt](https://github.com/Clinical-Genomics/target_capture_bed/files/4155908/ACC5812A1_1_97543299_98386605_Sambamba_cov_Above50.txt)

First, I didn't have the case folder but I manually created it and moved the bam file to this path /Users/annaengstrom/Downloads/case/mintpossum/analysis/bam/concatenated_ACC5812A1_XXXXXX_R.sorted.bam

**Comment by annaengstrom** [comment]
Sorry, but I just actually checked the two files, the one by @keyvanelhami and me, and they are different....?

**Comment by keyvanelhami** [comment]
@hassanfa We are trying to troubleshoot why my and Annas output looks different but we cannot identify why. The only differences we could find is that my output file has 190 lines and Anna 174 and that we have different versions of below tools. The coverage we get are totally different so I suspect that some tools might run differently in our computers.

Should I update my tools and rerun the script? Or do you think there is another reason to this?

**Anna:**
Snakemake v.5.9.1
bedops v. 2.4.37

**Keyvan:**
Snakemake: 5.4.5
bedops v. 2.4.36

**Comment by hassanfa** [comment]
Looking into it.

**Comment by hassanfa** [comment]
I got same result as Anna. It seems some regions have different coverage values. Maybe the source bam file is different?

An example:

```
anna_result:1	97547655	97547656	rs56155632	54	54	concatenated_ACC5812A1_XXXXXX_R
hassan_result:1	97547655	97547656	rs56155632	54	54	concatenated_ACC5812A1_XXXXXX_R
keyvan_result:1	97547655	97547656	rs56155632	126	126	concatenated_ACC5812A1_XXXXXX_R
```

**Comment by keyvanelhami** [comment]
```1	97547655	97547656	rs56155632	54	54	concatenated_ACC5812A1_XXXXXX_R
1	97547690	97547691	rs115462926	84	84	concatenated_ACC5812A1_XXXXXX_R
1	97547756	97547757	rs55792021	183	183	concatenated_ACC5812A1_XXXXXX_R
1	97547760	97547761	rs147947737	196	196	concatenated_ACC5812A1_XXXXXX_R
1	97547820	97547821	rs141776434	416	416	concatenated_ACC5812A1_XXXXXX_R
1	97547830	97547831	rs290854	481	481	concatenated_ACC5812A1_XXXXXX_R
1	97547868	97547870	rs377410137	784	780	concatenated_ACC5812A1_XXXXXX_R
1	97547876	97547877	rs375990495	865	865	concatenated_ACC5812A1_XXXXXX_R
1	97547906	97547907	rs368617815	1087	1087	concatenated_ACC5812A1_XXXXXX_R```

I got the same output now as @annaengstrom @hassanfa . The reason is that I used the original bam-file from the original analysis. The one I attached here is the downsampled one, that´s why I got higher coverage.

@hassanfa can I merge and pull request now?

**Comment by hassanfa** [comment]
I forgot to mention to name your Snake file all lowercase without `.py` extension, and place it `production/workflows/snp_annotation` or something similar.

**Comment by hassanfa** [comment]
@keyvanelhami I think you forgot to move the workflow to production/workflows/snp_annotation

**Comment by hassanfa** [comment]
@keyvanelhami Same thing we discussed with in PR #35 to organize files applies here as well.

**Pull request merged**
