### PR TITLE
Agilent v5

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds: Agilent sureselect version 5 

Check list if changes affect bed files:

- [x] Update shasum
- [x] Update annotations
- [x] Update filename if relevant
- [x] Update person who designed/changed it
- [x] Update bed file version
- [x] Update UCSC track
- [x] Update statusDB
- [ ] Deploy on Hasta
- [x] Update LIMS

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@hassanfa @annaengstrom @moahaegglund Could you review and give feedback on this PR. We have an old rerun case `usablestud`, that needs this bait set to start.

**Comment by annaengstrom** [comment]
Agilent v5 doesn't say much about the panel, is this an exome?

**Comment by henrikstranneheim** [comment]
> Agilent v5 doesn't say much about the panel, is this an exome?

Yes, all exons (whatever that means 😄 : 
From the track description
```
track name="Target Regions" description="Agilent SureSelect DNA - SureSelectXT Human All Exon V5 - Target regions of interest given as input to probe selection" color=0,0,128
# ## Agilent sureselect V5 target bed Clinical Genomics
```

**Comment by hassanfa** [comment]
Btw, before merging it'd be great to have update LIMS and statusDB.

**Comment by henrikstranneheim** [comment]
Great thx @hassanfa !

**Comment by annaengstrom** [comment]
> > Agilent v5 doesn't say much about the panel, is this an exome?
> 
> Yes, all exons (whatever that means 😄 :
> From the track description
> 
> ```
> track name="Target Regions" description="Agilent SureSelect DNA - SureSelectXT Human All Exon V5 - Target regions of interest given as input to probe selection" color=0,0,128
> # ## Agilent sureselect V5 target bed Clinical Genomics
> ```

Alright, the title is already long enough, so let's leave it as it is.

**Comment by annaengstrom** [comment]
Screenshot 2020-04-14 at 11 50 06
Screenshot 2020-04-14 at 11 50 00
Screenshot 2020-04-14 at 11 49 48

I have updated LIMS and statusDB. Does this look fine for you? I realize the old value for CRE was Agilent Sureselect CRE in LIMS and statusDB - which one do we want?

**Comment by henrikstranneheim** [comment]
@annaengstrom Nice! I think we need the versioned ones, like you have done. The designer column, panel size and genome version for CRE.v11.1 in Status is missing. And genom version is missing for agilent v5.

**Comment by henrikstranneheim** [comment]
@hassanfa Are we good to merge or is anything missing?

**Comment by hassanfa** [comment]
Of course, let's merge it.

**Pull request merged**
