### PR TITLE
twist comprehensive exome addition

### PR DESCRIPTION
**Pull request by hassanfa**
Check list if changes affect bed files:

- [x] Update shasum
- [x] Update annotations
- [x] Update filename if relevant
- [x] Update person who designed/changed it
- [x] Update bed file version
- [x] Update UCSC track
- [x] Update statusDB
~- [ ] Deploy on Hasta~
- [x] Update LIMS

1. Created a starting bed file from merging two exome and exome+refseq and sort and merge:

```
cat data_files/twistexome_8.1_hg19_design.bed \
   data_files/twistexomerefseq_9.1_hg19_design.bed \
   | awk '$1~/chr/' \
   | sort -k1,1 -k2,2n \
   | bedtools merge > data_files/twistexomecomprehensive_10.1_hg19_design.bed
```
2. Add header to file. (use your favorite editor)

3. Count bed size:

```
awk '$1~/chr/ {s+=$3-$2}END{print s}' data_files/twistexomecomprehensive_10.1_hg19_design.bed
```
4. Uploaded to UCSC:

image

### CODE REVIEW

**Comment by hassanfa** [comment]
@annaengstrom Here is the PR! I added the bed file and updated README.: https://github.com/Clinical-Genomics/target_capture_bed/tree/twist_comprehensive_exome

is comp_exome_10.1 a good shortname for it? or should it be exom_comp_10.1?

**Comment by annaengstrom** [comment]
> @annaengstrom Here is the PR! I added the bed file and updated README.: https://github.com/Clinical-Genomics/target_capture_bed/tree/twist_comprehensive_exome
> 
> is comp_exome_10.1 a good shortname for it? or should it be exom_comp_10.1?

We have "exome_refseq_9.1" so I think we should name it "exom**e**_comp_10.1". 

Same goes for the bed file name, to keep it consistent I would like to suggest to name it: "twistexomecomprehensive_10.1_hg19_design.bed", what do you think?

**Comment by hassanfa** [comment]
Makes sense. 👍 file names and short names are updated.

**Comment by hassanfa** [comment]
@annaengstrom merge as soon as you have finished those three remaining. I'll make a release tomorrow.

**Comment by annaengstrom** [comment]
StatusDB and LIMS updated for Twist Exome Comprehensive.

Screen Shot 2020-04-05 at 7 15 23 PM
Screen Shot 2020-04-05 at 7 15 14 PM

**Comment by annaengstrom** [comment]
I'm sorry but I am not sure about the step "Deploy on hasta" - what to do?

**Comment by hassanfa** [comment]
Nothing :-) that's for future when/if we get to that point. I striked through. Thanks.

**Pull request merged**
