### PR TITLE
Update README.md with Agilent Sureselect CRE

### PR DESCRIPTION
**Pull request by annaengstrom**
Check list if changes affect bed files:

- [x] Update shasum
- [x] Update annotations
- [x] Update filename if relevant
- [x] Update person who designed/changed it
- [x] Update bed file version
- [x] Update UCSC track
- [x] Update statusDB
~- [ ] Deploy on Hasta~
- [x] Update LIMS

### CODE REVIEW

**Comment by annaengstrom** [comment]
don't know what you think about this preposition, it doesn't follow the convention... should we try to push it towards it or leave it as it is? @hassanfa

**Comment by hassanfa** [comment]
It should be renamed and match to the naming convention.

**Comment by annaengstrom** [comment]
@henrikstranneheim for addition of Agilent CRE to this repo, it should be renamed to follow convention, would you like me to make a suggestion?

**Comment by henrikstranneheim** [comment]
I think you should name it according to the convention followed in this repo - for consistency

**Comment by henrikstranneheim** [comment]
@annaengstrom Please change it as you see fit

**Comment by henrikstranneheim** [comment]
Added according to you suggestions. The agilent file is big - I can remove the extra cols from the data_files if you like. Depends on the user case I guess (raw file or processed)
I also added the production file straigth in the dir and not under a pipeline as it should be pipeline agnostic. I move it if you want to.

**Comment by hassanfa** [comment]
Super! Thanks! I can take it from here and harmonize it with rest of bed files. 👍

**Comment by hassanfa** [comment]
Agilent sureselect added to UCSC:

image

**Comment by hassanfa** [comment]
README updated with panel size:

```
awk '$1~/chr/' data_files/agilentsureselectcre_11.1_hg19_design.bed \
| sort -k1,1 -k2,2n \
| bedtools merge \
| awk '$1~/chr/ {s+=$3-$2}END{print s}'
```

**Comment by hassanfa** [comment]
mip production bed file also has the same size:

```
awk '{s+=$3-$2}END{print s}' production/mip/agilentsureselectcre_11.1_hg19_design.bed
```
54098923

**Comment by henrikstranneheim** [comment]
👍

**Pull request merged**
