### PR TITLE
Adding SureSelect v1

### PR DESCRIPTION
**Pull request by annaengstrom**
Update with panel size when correct bed file has been provided from customer, see ticket 707381.

Check list if changes affect bed files:

- [x] Update shasum
- [x] Update annotations
- [x] Update filename if relevant
- [x] Update person who designed/changed it
- [x] Update bed file version
- [x] Add bed file
- [x] Update UCSC track
- [x] Update statusDB
- [ ] Deploy on Hasta
- [x] Update LIMS

### CODE REVIEW

**Comment by annaengstrom** [comment]
FYI @moahaegglund 

Updating statusdb when bed file is available from customer

**Comment by hassanfa** [comment]
A new bed file! 🎉  Could you please add bedfile to this PR as well? I can take it from there.

**Comment by annaengstrom** [comment]
> A new bed file! 🎉 Could you please add bedfile to this PR as well? I can take it from there.

done

**Comment by hassanfa** [comment]
@annaengstrom Updated bed file info.

Please update status db, we can merge it.

**Comment by annaengstrom** [comment]
Updated status db and LIMS (I suppose you need to fetch bed file from "LIMS" @moahaegglund )

Screen Shot 2020-06-01 at 2 54 50 PM
Screen Shot 2020-06-01 at 2 54 43 PM

**Comment by annaengstrom** [comment]
> @annaengstrom Updated bed file info.
> 
> Please update status db, we can merge it.

Thanks @hassanfa!! You can merge now.

**Pull request merged**
